# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Learning & Writing"
weight = 1
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Learning & Writing"
weight = 1