# Dependencies
markdown:         Kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            从容地狂奔
tagline:          ''
description:      '<a href=/#>Hi this is my blog</><br/> <a href=https://twitter.com/sbabybird>twitter</a><br /><a href=https://github.com/sbabybird>github</a><br/>敏而好学，杰而不傲</br>'
url:              http://sbabybird.github.io
baseurl:          /

author:
  name:           'sbabybird'
  url:            https://twitter.com/sbabybird

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:          sbabybird.github.com 
